//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class userClasses_variables
    {
        public int variable_id { get; set; }
        public int user_class_id { get; set; }
    
        public virtual userClasses_variables userClasses_variables1 { get; set; }
        public virtual userClasses_variables userClasses_variables2 { get; set; }
        public virtual userClasss userClasss { get; set; }
        public virtual variable variable { get; set; }
    }
}
